### ISSUE TITLE
Outlines is null for variations 

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-module-catalog#117]
Outlines is null for Variation. So, storefront could not create seo url for variation product.

Version info: 
- Module version: v2.21.1

### Expected behavior
Have Outlines collection as well as for product.

### Actual behavior
Outlines property is null

### Steps to reproduce
Try to load product with variations
https://admin-demo.virtocommerce.com/api/catalog/products/plenty?respGroup=ItemLarge
["8b7b07c165924a879392f4f51a6f7ce0"]

**Comment by OlegoO** [comment]
As workaround, I added fix on storefront side into CatalogConverterExtension.ToProduct method
````````````
			if (productDto.Outlines == null)
			{
				result.Url = $"~/product/{productDto.Id}";
			}
````````````

**Comment by tatarincev** [comment]
I think that it will be redundant for you mentioned case (use in the storefront for Url building) because the `main` product already has collections` Outlines` and it will be the same for all product variation. If `Outlines` required only for the variation correct  `Url` evaluations, just need use `Outlines` from parent product then. 
I'll prepare these fixes in both storefronts.

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/v2.21.2
