### ISSUE TITLE
The performance problems of index and query in catalog module

### ISSUE THREAD

**Issue by ruyi-kooboo** [VirtoCommerce/vc-module-catalog#55]
Hi,We recently encountered a problem, the scene is like this: we have ten thousand products, each product has 10 attributes, so that we in the database of product attribute value (PropertyValue) will be 100 thousand, the value of the property when establishing the index you will be query the database  and return all the property value. (VirtoCommerce.CatalogModule.Data.Repositories.CatalogRepositoryImpl.GetCategoriesByIds, Line174), the query time required about 1 min, we are mainly property value problems, but we found that late product pictures will encounter the same problem,can you give me a solutions?

**Comment by tatarincev** [comment]
@ruyi-kooboo  The performance of method GetCategoriesByIds shouldn't  depend on total products quantity in DB.
Can you send your catalog data privately for detailed examination?  Export &  Import -> Choose Catalog without binary data.

**Comment by zhangpeng-kooboo** [comment]
Hi @tatarincev ,

Mainly due to the following line in the GetCategoriesByIds

`
//Load category property values by separate query
var propertyValues = PropertyValues.Where(x => categoriesIds.Contains(x.CategoryId)).ToArray();
`

We only have 4 categories in our system, two big categories, for those two big categories each one contains about 10,000 products, so around 100,000 property values for each category.

When the system start indexing a product, it will try to look up categories for this product. And the above query triggered try to load 100,000 property values into memory at once. Then the system is start paining. Of course we can scale up the Azure instance size / Azure sql instance size to improve this a little bit, but seem try to load 100,000 records at once for a product is not a good idea.

Do you have any suggestions, maybe it was added by a good reason. 

Thks,
ZP

**Comment by tatarincev** [comment]
PropertyValue table has three foreign key columns. And only one of them sets in depending on the associated object type.  
![image](https://user-images.githubusercontent.com/7566324/31764304-12939e5c-b4c1-11e7-96d8-2387fc59427b.png)
For your case with only two categories, this line will select only those records which have values in  CategoryId column only.
Could you check PropertyValue table records in your DB?

**Comment by zhangpeng-kooboo** [comment]
Thks @tatarincev you are pointing us to the right direction. Our developers imported products from ERP to VirtoCommerce SQL database directly and filled in the category id but should be 'null'.

**Comment by tatarincev** [comment]
Glad to help old friends :)

**Comment by ruyi-kooboo** [comment]
Thank you very much~
