### ISSUE TITLE
Expose the list of characters that are illegal in SKUs

### ISSUE THREAD

**Issue by j-mok** [VirtoCommerce/vc-module-catalog#635]
Illegal characters that `ProductValidator` looks for in a catalog product's SKU are currently hidden away in a private field (`_illegalCodeChars`). I think these should be public and available for consumption from other modules. This is important i.e. when importing products from external sources where SKUs may need to be escaped before using them in Virto. In such a case I currently need to copy the illegal characters into the encoder instead of referencing them.

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-8229 has been created

**Comment by Dan-BV** [comment]
Hi @j-mok !
We apologize for the long response time. 
At the moment we do not plan to overlap `_illegalCodeChars` because it is built on compatibility with search engines.
You can override with your validator as in the example https://github.com/VirtoCommerce/vc-module-catalog/blob/4d8f92219f7c6c1cd2b072d1407a05a3f44613bc/samples/VirtoCommerce.CatalogModule2.Web/Services/ItemService.cs#L17

**Comment by j-mok** [comment]
Can you elaborate a bit on the search engine compatibility part? If we are to override validation and allow broader set of characters, we want to know what we're losing/risking.

**Comment by Dan-BV** [comment]
For compatibility with search engines, we use generally accepted best practices for SKU generation: 

- Create a coding system
- Establish a standard format
- Avoid using similar letters and numbers
- Make SKUs easy to understand and identify
- Don’t start SKUs with the number 0
- Ensure each SKU is unique
- Don’t use spaces

**Comment by j-mok** [comment]
OK, thanks, I guess that settles it.
